/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AffectedResultsSchema200', 'model/NoDataSchema400', 'model/NoDataSchema401', 'model/V21SchemasDeleteCustomAppConfigurationSchema', 'model/V21SchemasGetIndicatorSchemaMany200', 'model/V21SchemasGetUserConfigSchemaMany200', 'model/V21SchemasGlobalExclusionsDetailsMany200', 'model/V21SchemasGlobalExclusionsSchema', 'model/V21SchemasIOCDeleteSchema', 'model/V21SchemasPostCustomAppConfigurationSchema', 'model/V21SchemasPostIndicatorSchemaMany200', 'model/V21SchemasPostThreatIntelligenceSchema', 'model/V21SchemasPostUamAlertObservablesDataSchema', 'model/V21SchemasPostUserConfigSchema', 'model/V21SchemasUserConfigFilterSchema'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AffectedResultsSchema200'), require('../model/NoDataSchema400'), require('../model/NoDataSchema401'), require('../model/V21SchemasDeleteCustomAppConfigurationSchema'), require('../model/V21SchemasGetIndicatorSchemaMany200'), require('../model/V21SchemasGetUserConfigSchemaMany200'), require('../model/V21SchemasGlobalExclusionsDetailsMany200'), require('../model/V21SchemasGlobalExclusionsSchema'), require('../model/V21SchemasIOCDeleteSchema'), require('../model/V21SchemasPostCustomAppConfigurationSchema'), require('../model/V21SchemasPostIndicatorSchemaMany200'), require('../model/V21SchemasPostThreatIntelligenceSchema'), require('../model/V21SchemasPostUamAlertObservablesDataSchema'), require('../model/V21SchemasPostUserConfigSchema'), require('../model/V21SchemasUserConfigFilterSchema'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.ThreatIntelligenceApi = factory(root.S1MgmtApi.ApiClient, root.S1MgmtApi.AffectedResultsSchema200, root.S1MgmtApi.NoDataSchema400, root.S1MgmtApi.NoDataSchema401, root.S1MgmtApi.V21SchemasDeleteCustomAppConfigurationSchema, root.S1MgmtApi.V21SchemasGetIndicatorSchemaMany200, root.S1MgmtApi.V21SchemasGetUserConfigSchemaMany200, root.S1MgmtApi.V21SchemasGlobalExclusionsDetailsMany200, root.S1MgmtApi.V21SchemasGlobalExclusionsSchema, root.S1MgmtApi.V21SchemasIOCDeleteSchema, root.S1MgmtApi.V21SchemasPostCustomAppConfigurationSchema, root.S1MgmtApi.V21SchemasPostIndicatorSchemaMany200, root.S1MgmtApi.V21SchemasPostThreatIntelligenceSchema, root.S1MgmtApi.V21SchemasPostUamAlertObservablesDataSchema, root.S1MgmtApi.V21SchemasPostUserConfigSchema, root.S1MgmtApi.V21SchemasUserConfigFilterSchema);
  }
}(this, function(ApiClient, AffectedResultsSchema200, NoDataSchema400, NoDataSchema401, V21SchemasDeleteCustomAppConfigurationSchema, V21SchemasGetIndicatorSchemaMany200, V21SchemasGetUserConfigSchemaMany200, V21SchemasGlobalExclusionsDetailsMany200, V21SchemasGlobalExclusionsSchema, V21SchemasIOCDeleteSchema, V21SchemasPostCustomAppConfigurationSchema, V21SchemasPostIndicatorSchemaMany200, V21SchemasPostThreatIntelligenceSchema, V21SchemasPostUamAlertObservablesDataSchema, V21SchemasPostUserConfigSchema, V21SchemasUserConfigFilterSchema) {
  'use strict';

  /**
   * ThreatIntelligence service.
   * @module api/ThreatIntelligenceApi
   * @version 2.1
   */

  /**
   * Constructs a new ThreatIntelligenceApi. 
   * @alias module:api/ThreatIntelligenceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the webApiPrivateInternalIocsGlobalExclusionsDelete operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateInternalIocsGlobalExclusionsDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AffectedResultsSchema200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete IOCs values from iocs_global_exclusions table.
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasGlobalExclusionsSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateInternalIocsGlobalExclusionsDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AffectedResultsSchema200}
     */
    this.webApiPrivateInternalIocsGlobalExclusionsDelete = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AffectedResultsSchema200;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/internal/iocs/global-exclusions', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateInternalIocsGlobalExclusionsGet operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateInternalIocsGlobalExclusionsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V21SchemasGlobalExclusionsDetailsMany200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the Threat Intelligence user config that match the filter.
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateInternalIocsGlobalExclusionsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V21SchemasGlobalExclusionsDetailsMany200}
     */
    this.webApiPrivateInternalIocsGlobalExclusionsGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = V21SchemasGlobalExclusionsDetailsMany200;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/internal/iocs/global-exclusions', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateInternalIocsGlobalExclusionsPost operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateInternalIocsGlobalExclusionsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AffectedResultsSchema200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Post IOCs values to iocs_global_exclusions table.
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasGlobalExclusionsSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateInternalIocsGlobalExclusionsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AffectedResultsSchema200}
     */
    this.webApiPrivateInternalIocsGlobalExclusionsPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AffectedResultsSchema200;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/internal/iocs/global-exclusions', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateThreatIntelligenceAlertsalertIdIocsPost operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceAlertsalertIdIocsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get IOC enrichment for alert
     * Get ioc enrichment of a specified alert and the events associated with the alert.
     * @param {String} alertId UAM Alert ID. Example: \"225494730938493804\".
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasPostUamAlertObservablesDataSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceAlertsalertIdIocsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.webApiPrivateThreatIntelligenceAlertsalertIdIocsPost = function(alertId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling webApiPrivateThreatIntelligenceAlertsalertIdIocsPost");
      }


      var pathParams = {
        'alert_id': alertId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/threat-intelligence/alerts/{alert_id}/iocs', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateThreatIntelligenceCustomAppConfigDelete operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceCustomAppConfigDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AffectedResultsSchema200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete custom config app
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasDeleteCustomAppConfigurationSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceCustomAppConfigDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AffectedResultsSchema200}
     */
    this.webApiPrivateThreatIntelligenceCustomAppConfigDelete = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AffectedResultsSchema200;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/threat-intelligence/custom-app-config', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateThreatIntelligenceCustomAppConfigPost operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceCustomAppConfigPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AffectedResultsSchema200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update custom custom app configuration per scope
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasPostCustomAppConfigurationSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceCustomAppConfigPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AffectedResultsSchema200}
     */
    this.webApiPrivateThreatIntelligenceCustomAppConfigPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AffectedResultsSchema200;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/threat-intelligence/custom-app-config', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateThreatIntelligenceKnowledgeHuburiGet operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceKnowledgeHuburiGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Knowledge hub data
     * Get Threat intelligence knowledge hub related data.
     * @param {String} uri proxy
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceKnowledgeHuburiGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.webApiPrivateThreatIntelligenceKnowledgeHuburiGet = function(uri, callback) {
      var postBody = null;

      // verify the required parameter 'uri' is set
      if (uri === undefined || uri === null) {
        throw new Error("Missing the required parameter 'uri' when calling webApiPrivateThreatIntelligenceKnowledgeHuburiGet");
      }


      var pathParams = {
        'uri': uri
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/threat-intelligence/knowledge-hub/{uri}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiPrivateThreatIntelligenceThreatsthreatIdIndicatorsGet operation.
     * @callback module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceThreatsthreatIdIndicatorsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get IOC enrichment for threat
     * Get ioc enrichment of a specified threat and the events associated with the threat.
     * @param {String} threatId Threat ID. Example: \"225494730938493804\".
     * @param {module:api/ThreatIntelligenceApi~webApiPrivateThreatIntelligenceThreatsthreatIdIndicatorsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.webApiPrivateThreatIntelligenceThreatsthreatIdIndicatorsGet = function(threatId, callback) {
      var postBody = null;

      // verify the required parameter 'threatId' is set
      if (threatId === undefined || threatId === null) {
        throw new Error("Missing the required parameter 'threatId' when calling webApiPrivateThreatIntelligenceThreatsthreatIdIndicatorsGet");
      }


      var pathParams = {
        'threat_id': threatId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/web/api/v2.1/private/threat-intelligence/threats/{threat_id}/indicators', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiThreatIntelligenceIocsDelete operation.
     * @callback module:api/ThreatIntelligenceApi~webApiThreatIntelligenceIocsDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AffectedResultsSchema200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete IOCs
     * Delete an IoC from the Threat Intelligence database that matches a filter using the accountID and one other field.
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasIOCDeleteSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiThreatIntelligenceIocsDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AffectedResultsSchema200}
     */
    this.webApiThreatIntelligenceIocsDelete = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AffectedResultsSchema200;

      return this.apiClient.callApi(
        '/web/api/v2.1/threat-intelligence/iocs', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiThreatIntelligenceIocsGet operation.
     * @callback module:api/ThreatIntelligenceApi~webApiThreatIntelligenceIocsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V21SchemasGetIndicatorSchemaMany200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get IOCs
     * Get the IOCs of a specified Account that match the filter.
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.descriptionContains Free-text filter by the description of the indicator (supports multiple values). Example: \"Malicious-activity\".
     * @param {Date} opts.uploadTimeGt The time at which the Threat Intelligence indicator was uploaded to SentinelOne DB greater than. Example: \"2022-07-13T20:33:29.007906Z\".
     * @param {Date} opts.updatedAtGt The time at which the indicator was last updated in SentinelOne DB  greater than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {String} opts.categoryIn The categories of the Threat Intelligence indicator, e.g.  the malware type associated with the IOC
     * @param {Number} opts.limit Limit number of returned items (1-1000). Example: \"10\". (default to 10)
     * @param {Date} opts.updatedAtGte The time at which the indicator was last updated in SentinelOne DB  greater or equal than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {Array.<String>} opts.creatorContains Free-text filter by the user uploaded the Threat Intelligence indicator (supports multiple values). Example: \"admin@sentinelone.com\".
     * @param {Boolean} opts.tenant Indicates a tenant scope request
     * @param {module:model/String} opts.sortBy The column to sort the results by. Example: \"id\". (default to null)
     * @param {Boolean} opts.skipCount If true, total number of items will not be calculated, which speeds up execution time. (default to null)
     * @param {Date} opts.creationTimeGte Creation Time as set by the user greater or equal than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {Number} opts.skip Skip first number of items (0-1000). To iterate over more than 1000 items,  use \"cursor\". Example: \"150\".
     * @param {Date} opts.creationTimeGt Creation Time as set by the user greater than. Example: \"2021-07-12T20:33:29.007906Z\".
     * @param {module:model/String} opts.type The type of the Threat Intelligence indicator. Example: \"IPv4\".
     * @param {module:model/String} opts.sortOrder Sort direction. Example: \"asc\". (default to null)
     * @param {Date} opts.creationTimeLte Creation Time as set by the user lesser or equal than. Example: \"2021-07-11T20:33:29.007906Z\".
     * @param {Date} opts.creationTimeLt Creation Time as set by the user lesser than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {String} opts.batchId Unique ID of the uploaded indicators batch. Example: \"atmtn000000028a881bcf939dc6d92ab55443\".
     * @param {String} opts.externalId The unique identifier of the indicator as provided by the Threat Intelligence source. Example: \"e277603e-1060-5ad4-9937-c26c97f1ca68\".
     * @param {Date} opts.updatedAtLt The time at which the indicator was last updated in SentinelOne DB  lesser than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {Date} opts.updatedAtLte The time at which the indicator was last updated in SentinelOne DB  lesser or equal than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {Array.<String>} opts.accountIds List of Account IDs to filter by. Example: \"4,2,6,4,1,8,0,3,0,2,1,2,0,7,3,7,6,2\".
     * @param {Array.<String>} opts.source List of the sources of the identified Threat Intelligence indicator. Example: \"AlienVault\".
     * @param {String} opts.cursor Cursor position returned by the last request. Use to iterate over more than 1000 items. Example: \"YWdlbnRfaWQ6NTgwMjkzODE=\". (default to null)
     * @param {Boolean} opts.countOnly If true, only total number of items will be returned, without any of the actual objects. (default to false)
     * @param {String} opts.value The value of the Threat Intelligence indicator. Example: \"175.45.176.1\".
     * @param {Date} opts.uploadTimeLte The time at which the Threat Intelligence indicator was uploaded to SentinelOne DB lesser or equal than. Example: \"2022-07-13T20:33:29.007906Z\".
     * @param {Array.<String>} opts.uuids A list of unique Ids of the parent process of the indicator of compromise. Example: \"2,c,f,f,a,e,8,7,1,1,9,7,f,2,0,d,8,6,4,f,e,8,3,6,3,e,e,e,6,6,5,1\".
     * @param {Array.<String>} opts.nameContains Free-text filter by the Indicator name (supports multiple values). Example: \"foo.dll\".
     * @param {Date} opts.uploadTimeLt The time at which the Threat Intelligence indicator was uploaded to SentinelOne DB lesser than. Example: \"2021-07-13T20:33:29.007906Z\".
     * @param {Date} opts.uploadTimeGte The time at which the Threat Intelligence indicator was uploaded to SentinelOne DB greater or equal than. Example: \"2022-07-13T20:33:29.007906Z\".
     * @param {module:api/ThreatIntelligenceApi~webApiThreatIntelligenceIocsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V21SchemasGetIndicatorSchemaMany200}
     */
    this.webApiThreatIntelligenceIocsGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'uploadTime__gt': opts['uploadTimeGt'],
        'updatedAt__gt': opts['updatedAtGt'],
        'category__in': opts['categoryIn'],
        'limit': opts['limit'],
        'updatedAt__gte': opts['updatedAtGte'],
        'tenant': opts['tenant'],
        'sortBy': opts['sortBy'],
        'skipCount': opts['skipCount'],
        'creationTime__gte': opts['creationTimeGte'],
        'skip': opts['skip'],
        'creationTime__gt': opts['creationTimeGt'],
        'type': opts['type'],
        'sortOrder': opts['sortOrder'],
        'creationTime__lte': opts['creationTimeLte'],
        'creationTime__lt': opts['creationTimeLt'],
        'batchId': opts['batchId'],
        'externalId': opts['externalId'],
        'updatedAt__lt': opts['updatedAtLt'],
        'updatedAt__lte': opts['updatedAtLte'],
        'cursor': opts['cursor'],
        'countOnly': opts['countOnly'],
        'value': opts['value'],
        'uploadTime__lte': opts['uploadTimeLte'],
        'uploadTime__lt': opts['uploadTimeLt'],
        'uploadTime__gte': opts['uploadTimeGte'],
      };
      var collectionQueryParams = {
        'description__contains': {
          value: opts['descriptionContains'],
          collectionFormat: 'csv'
        },
        'creator__contains': {
          value: opts['creatorContains'],
          collectionFormat: 'csv'
        },
        'accountIds': {
          value: opts['accountIds'],
          collectionFormat: 'csv'
        },
        'source': {
          value: opts['source'],
          collectionFormat: 'csv'
        },
        'uuids': {
          value: opts['uuids'],
          collectionFormat: 'csv'
        },
        'name__contains': {
          value: opts['nameContains'],
          collectionFormat: 'csv'
        },
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = V21SchemasGetIndicatorSchemaMany200;

      return this.apiClient.callApi(
        '/web/api/v2.1/threat-intelligence/iocs', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiThreatIntelligenceIocsPost operation.
     * @callback module:api/ThreatIntelligenceApi~webApiThreatIntelligenceIocsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V21SchemasPostIndicatorSchemaMany200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create IOCs
     * Add an IoC to the Threat Intelligence database. <br>These values under data are required fields: \"source\", \"type\", \"value\", and \"method\". <br>\"Type\" and \"method\" must be in upper case.<br>The \"validUntil\" field is mandatory, and must contain a date, for example, 2021-03-20 09:14:47.779000. \"validUntil\" determines when the IOC expires.<br>If the expiration date (\"validUntil\") is left blank, by default it will be the upload date plus a default offset value:<br>- 14 days for IPs<br>- 90 days for URLs and domains<br>- 180 days for file hashes (SHA1, SHA256, and MD5)<br>The maximum offset values allowed are:<br>- 30 days for IPs<br>- 180 days for URLs and Domains<br>- 180 days for hashes (SHA1, SHA256, and MD5)<br>The upload date is when the API gets a request to create an IOC.<br>If the expiration date is later than the upload date plus the the maximum offset value allowed, it will be adjusted to the upload date plus the maximum offset value allowed.
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasPostThreatIntelligenceSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiThreatIntelligenceIocsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V21SchemasPostIndicatorSchemaMany200}
     */
    this.webApiThreatIntelligenceIocsPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V21SchemasPostIndicatorSchemaMany200;

      return this.apiClient.callApi(
        '/web/api/v2.1/threat-intelligence/iocs', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiThreatIntelligenceUserConfigDelete operation.
     * @callback module:api/ThreatIntelligenceApi~webApiThreatIntelligenceUserConfigDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AffectedResultsSchema200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Threat Intelligence user config
     * Delete Threat Intelligence user config that match the filter.
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasUserConfigFilterSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiThreatIntelligenceUserConfigDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AffectedResultsSchema200}
     */
    this.webApiThreatIntelligenceUserConfigDelete = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AffectedResultsSchema200;

      return this.apiClient.callApi(
        '/web/api/v2.1/threat-intelligence/user-config', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiThreatIntelligenceUserConfigGet operation.
     * @callback module:api/ThreatIntelligenceApi~webApiThreatIntelligenceUserConfigGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V21SchemasGetUserConfigSchemaMany200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Threat Intelligence user config
     * Get the Threat Intelligence user config that match the filter.
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.tenant Indicates a tenant scope request
     * @param {Array.<String>} opts.accountIds List of Account IDs to filter by. Example: \"4,2,6,4,1,8,0,3,0,2,1,2,0,7,3,7,6,2\".
     * @param {module:api/ThreatIntelligenceApi~webApiThreatIntelligenceUserConfigGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V21SchemasGetUserConfigSchemaMany200}
     */
    this.webApiThreatIntelligenceUserConfigGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'tenant': opts['tenant'],
      };
      var collectionQueryParams = {
        'accountIds': {
          value: opts['accountIds'],
          collectionFormat: 'csv'
        },
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = V21SchemasGetUserConfigSchemaMany200;

      return this.apiClient.callApi(
        '/web/api/v2.1/threat-intelligence/user-config', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiThreatIntelligenceUserConfigPost operation.
     * @callback module:api/ThreatIntelligenceApi~webApiThreatIntelligenceUserConfigPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V21SchemasGetUserConfigSchemaMany200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Threat Intelligence user config
     * Create Threat Intelligence user config.
     * @param {Object} opts Optional parameters
     * @param {module:model/V21SchemasPostUserConfigSchema} opts.body 
     * @param {module:api/ThreatIntelligenceApi~webApiThreatIntelligenceUserConfigPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V21SchemasGetUserConfigSchemaMany200}
     */
    this.webApiThreatIntelligenceUserConfigPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiTokenAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V21SchemasGetUserConfigSchemaMany200;

      return this.apiClient.callApi(
        '/web/api/v2.1/threat-intelligence/user-config', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
