/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AgentsSchemasAgentPassphraseSchemaMany200Data', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.AgentsSchemasAgentPassphraseSchemaMany200Data();
      });

      it('should create an instance of AgentsSchemasAgentPassphraseSchemaMany200Data', function() {
        // TODO: update the code to test AgentsSchemasAgentPassphraseSchemaMany200Data
        expect(instance).to.be.a(S1MgmtApi.AgentsSchemasAgentPassphraseSchemaMany200Data);
      });

      it('should have the property lastLoggedInUserName (base name: "lastLoggedInUserName")', function() {
        // TODO: update the code to test the property lastLoggedInUserName
        expect(instance).to.have.property('lastLoggedInUserName');
        // expect(instance.lastLoggedInUserName).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property passphrase (base name: "passphrase")', function() {
        // TODO: update the code to test the property passphrase
        expect(instance).to.have.property('passphrase');
        // expect(instance.passphrase).to.be(expectedValueLiteral);
      });

      it('should have the property domain (base name: "domain")', function() {
        // TODO: update the code to test the property domain
        expect(instance).to.have.property('domain');
        // expect(instance.domain).to.be(expectedValueLiteral);
      });

      it('should have the property uuid (base name: "uuid")', function() {
        // TODO: update the code to test the property uuid
        expect(instance).to.have.property('uuid');
        // expect(instance.uuid).to.be(expectedValueLiteral);
      });

      it('should have the property computerName (base name: "computerName")', function() {
        // TODO: update the code to test the property computerName
        expect(instance).to.have.property('computerName');
        // expect(instance.computerName).to.be(expectedValueLiteral);
      });

    });
  });

}));
