/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ApplicationsSchemasCveViewSchemaMany200Data', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.ApplicationsSchemasCveViewSchemaMany200Data();
      });

      it('should create an instance of ApplicationsSchemasCveViewSchemaMany200Data', function() {
        // TODO: update the code to test ApplicationsSchemasCveViewSchemaMany200Data
        expect(instance).to.be.a(S1MgmtApi.ApplicationsSchemasCveViewSchemaMany200Data);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property score (base name: "score")', function() {
        // TODO: update the code to test the property score
        expect(instance).to.have.property('score');
        // expect(instance.score).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property publishedAt (base name: "publishedAt")', function() {
        // TODO: update the code to test the property publishedAt
        expect(instance).to.have.property('publishedAt');
        // expect(instance.publishedAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property cveId (base name: "cveId")', function() {
        // TODO: update the code to test the property cveId
        expect(instance).to.have.property('cveId');
        // expect(instance.cveId).to.be(expectedValueLiteral);
      });

      it('should have the property riskLevel (base name: "riskLevel")', function() {
        // TODO: update the code to test the property riskLevel
        expect(instance).to.have.property('riskLevel');
        // expect(instance.riskLevel).to.be(expectedValueLiteral);
      });

      it('should have the property link (base name: "link")', function() {
        // TODO: update the code to test the property link
        expect(instance).to.have.property('link');
        // expect(instance.link).to.be(expectedValueLiteral);
      });

    });
  });

}));
