/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ForensicsApplicationDetailsContentFields200DataResultSummaryOverviewRegistry', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.ForensicsApplicationDetailsContentFields200DataResultSummaryOverviewRegistry();
      });

      it('should create an instance of ForensicsApplicationDetailsContentFields200DataResultSummaryOverviewRegistry', function() {
        // TODO: update the code to test ForensicsApplicationDetailsContentFields200DataResultSummaryOverviewRegistry
        expect(instance).to.be.a(S1MgmtApi.ForensicsApplicationDetailsContentFields200DataResultSummaryOverviewRegistry);
      });

      it('should have the property persistence (base name: "persistence")', function() {
        // TODO: update the code to test the property persistence
        expect(instance).to.have.property('persistence');
        // expect(instance.persistence).to.be(expectedValueLiteral);
      });

      it('should have the property security (base name: "security")', function() {
        // TODO: update the code to test the property security
        expect(instance).to.have.property('security');
        // expect(instance.security).to.be(expectedValueLiteral);
      });

      it('should have the property stealth (base name: "stealth")', function() {
        // TODO: update the code to test the property stealth
        expect(instance).to.have.property('stealth');
        // expect(instance.stealth).to.be(expectedValueLiteral);
      });

    });
  });

}));
