/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('NotificationsSchemasNotificationSettingsPutSchemaData', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.NotificationsSchemasNotificationSettingsPutSchemaData();
      });

      it('should create an instance of NotificationsSchemasNotificationSettingsPutSchemaData', function() {
        // TODO: update the code to test NotificationsSchemasNotificationSettingsPutSchemaData
        expect(instance).to.be.a(S1MgmtApi.NotificationsSchemasNotificationSettingsPutSchemaData);
      });

      it('should have the property configurations (base name: "configurations")', function() {
        // TODO: update the code to test the property configurations
        expect(instance).to.have.property('configurations');
        // expect(instance.configurations).to.be(expectedValueLiteral);
      });

      it('should have the property notifications (base name: "notifications")', function() {
        // TODO: update the code to test the property notifications
        expect(instance).to.have.property('notifications');
        // expect(instance.notifications).to.be(expectedValueLiteral);
      });

      it('should have the property lastModified (base name: "lastModified")', function() {
        // TODO: update the code to test the property lastModified
        expect(instance).to.have.property('lastModified');
        // expect(instance.lastModified).to.be(expectedValueLiteral);
      });

    });
  });

}));
