/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SitesSitePutSchemaDataPolicyDvAttributesPerEventTypeRegistry', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.SitesSitePutSchemaDataPolicyDvAttributesPerEventTypeRegistry();
      });

      it('should create an instance of SitesSitePutSchemaDataPolicyDvAttributesPerEventTypeRegistry', function() {
        // TODO: update the code to test SitesSitePutSchemaDataPolicyDvAttributesPerEventTypeRegistry
        expect(instance).to.be.a(S1MgmtApi.SitesSitePutSchemaDataPolicyDvAttributesPerEventTypeRegistry);
      });

      it('should have the property dvEventTypeRegistryKeySecurityChanged (base name: "dvEventTypeRegistryKeySecurityChanged")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryKeySecurityChanged
        expect(instance).to.have.property('dvEventTypeRegistryKeySecurityChanged');
        // expect(instance.dvEventTypeRegistryKeySecurityChanged).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryValueDeleted (base name: "dvEventTypeRegistryValueDeleted")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryValueDeleted
        expect(instance).to.have.property('dvEventTypeRegistryValueDeleted');
        // expect(instance.dvEventTypeRegistryValueDeleted).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryValueModified (base name: "dvEventTypeRegistryValueModified")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryValueModified
        expect(instance).to.have.property('dvEventTypeRegistryValueModified');
        // expect(instance.dvEventTypeRegistryValueModified).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryKeyRename (base name: "dvEventTypeRegistryKeyRename")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryKeyRename
        expect(instance).to.have.property('dvEventTypeRegistryKeyRename');
        // expect(instance.dvEventTypeRegistryKeyRename).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryKeyCreated (base name: "dvEventTypeRegistryKeyCreated")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryKeyCreated
        expect(instance).to.have.property('dvEventTypeRegistryKeyCreated');
        // expect(instance.dvEventTypeRegistryKeyCreated).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryValueCreated (base name: "dvEventTypeRegistryValueCreated")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryValueCreated
        expect(instance).to.have.property('dvEventTypeRegistryValueCreated');
        // expect(instance.dvEventTypeRegistryValueCreated).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryKeyImport (base name: "dvEventTypeRegistryKeyImport")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryKeyImport
        expect(instance).to.have.property('dvEventTypeRegistryKeyImport');
        // expect(instance.dvEventTypeRegistryKeyImport).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryKeyDelete (base name: "dvEventTypeRegistryKeyDelete")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryKeyDelete
        expect(instance).to.have.property('dvEventTypeRegistryKeyDelete');
        // expect(instance.dvEventTypeRegistryKeyDelete).to.be(expectedValueLiteral);
      });

      it('should have the property dvEventTypeRegistryKeyExport (base name: "dvEventTypeRegistryKeyExport")', function() {
        // TODO: update the code to test the property dvEventTypeRegistryKeyExport
        expect(instance).to.have.property('dvEventTypeRegistryKeyExport');
        // expect(instance.dvEventTypeRegistryKeyExport).to.be(expectedValueLiteral);
      });

    });
  });

}));
