/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('V21DataExporterSchemaPutDestinationProfileRequestSchemaData', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.V21DataExporterSchemaPutDestinationProfileRequestSchemaData();
      });

      it('should create an instance of V21DataExporterSchemaPutDestinationProfileRequestSchemaData', function() {
        // TODO: update the code to test V21DataExporterSchemaPutDestinationProfileRequestSchemaData
        expect(instance).to.be.a(S1MgmtApi.V21DataExporterSchemaPutDestinationProfileRequestSchemaData);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property apiUrl (base name: "apiUrl")', function() {
        // TODO: update the code to test the property apiUrl
        expect(instance).to.have.property('apiUrl');
        // expect(instance.apiUrl).to.be(expectedValueLiteral);
      });

      it('should have the property apiKey (base name: "apiKey")', function() {
        // TODO: update the code to test the property apiKey
        expect(instance).to.have.property('apiKey');
        // expect(instance.apiKey).to.be(expectedValueLiteral);
      });

      it('should have the property isDefault (base name: "isDefault")', function() {
        // TODO: update the code to test the property isDefault
        expect(instance).to.have.property('isDefault');
        // expect(instance.isDefault).to.be(expectedValueLiteral);
      });

    });
  });

}));
