/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S1MgmtApi);
  }
}(this, function(expect, S1MgmtApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('V21ProvisioningSchemasTenantWithUsersResponse200Data', function() {
      beforeEach(function() {
        instance = new S1MgmtApi.V21ProvisioningSchemasTenantWithUsersResponse200Data();
      });

      it('should create an instance of V21ProvisioningSchemasTenantWithUsersResponse200Data', function() {
        // TODO: update the code to test V21ProvisioningSchemasTenantWithUsersResponse200Data
        expect(instance).to.be.a(S1MgmtApi.V21ProvisioningSchemasTenantWithUsersResponse200Data);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property adminUser (base name: "adminUser")', function() {
        // TODO: update the code to test the property adminUser
        expect(instance).to.have.property('adminUser');
        // expect(instance.adminUser).to.be(expectedValueLiteral);
      });

      it('should have the property users (base name: "users")', function() {
        // TODO: update the code to test the property users
        expect(instance).to.have.property('users');
        // expect(instance.users).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

    });
  });

}));
