/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.ExclusionsSchemasDeleteExclusionSchemaData = factory(root.S1MgmtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ExclusionsSchemasDeleteExclusionSchemaData model module.
   * @module model/ExclusionsSchemasDeleteExclusionSchemaData
   * @version 2.1
   */

  /**
   * Constructs a new <code>ExclusionsSchemasDeleteExclusionSchemaData</code>.
   * Data
   * @alias module:model/ExclusionsSchemasDeleteExclusionSchemaData
   * @class
   * @param ids {Array.<String>} Ids
   */
  var exports = function(ids) {
    this.ids = ids;
  };

  /**
   * Constructs a <code>ExclusionsSchemasDeleteExclusionSchemaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExclusionsSchemasDeleteExclusionSchemaData} obj Optional instance to populate.
   * @return {module:model/ExclusionsSchemasDeleteExclusionSchemaData} The populated <code>ExclusionsSchemasDeleteExclusionSchemaData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ids'))
        obj.ids = ApiClient.convertToType(data['ids'], ['String']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * Ids
   * @member {Array.<String>} ids
   */
  exports.prototype.ids = undefined;

  /**
   * Type
   * @member {module:model/ExclusionsSchemasDeleteExclusionSchemaData.TypeEnum} type
   */
  exports.prototype.type = undefined;



  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "path"
     * @const
     */
    path: "path",

    /**
     * value: "certificate"
     * @const
     */
    certificate: "certificate",

    /**
     * value: "browser"
     * @const
     */
    browser: "browser",

    /**
     * value: "file_type"
     * @const
     */
    fileType: "file_type",

    /**
     * value: "white_hash"
     * @const
     */
    whiteHash: "white_hash"
  };

  return exports;

}));
