/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData = factory(root.S1MgmtApi.ApiClient, root.S1MgmtApi.ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions);
  }
}(this, function(ApiClient, ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions) {
  'use strict';

  /**
   * The ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData model module.
   * @module model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData
   * @version 2.1
   */

  /**
   * Constructs a new <code>ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData</code>.
   * Data
   * @alias module:model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData
   * @class
   * @param exclusions {Array.<module:model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions>} Exclusions
   */
  var exports = function(exclusions) {
    this.exclusions = exclusions;
  };

  /**
   * Constructs a <code>ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData} obj Optional instance to populate.
   * @return {module:model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData} The populated <code>ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('exclusions'))
        obj.exclusions = ApiClient.convertToType(data['exclusions'], [ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions]);
    }
    return obj;
  }

  /**
   * Exclusions
   * @member {Array.<module:model/ExclusionsDeleteSchemaUnifiedExclusionSchemaDeleteRequestDataExclusions>} exclusions
   */
  exports.prototype.exclusions = undefined;


  return exports;

}));
