/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.FiltersFiltersUpdateFilterSchemaDataFilterFields = factory(root.S1MgmtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The FiltersFiltersUpdateFilterSchemaDataFilterFields model module.
   * @module model/FiltersFiltersUpdateFilterSchemaDataFilterFields
   * @version 2.1
   */

  /**
   * Constructs a new <code>FiltersFiltersUpdateFilterSchemaDataFilterFields</code>.
   * A set of parameters to filter by (If supplied, replaces existing parameter set
   * @alias module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FiltersFiltersUpdateFilterSchemaDataFilterFields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields} obj Optional instance to populate.
   * @return {module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields} The populated <code>FiltersFiltersUpdateFilterSchemaDataFilterFields</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('agentVersionsNin'))
        obj.agentVersionsNin = ApiClient.convertToType(data['agentVersionsNin'], ['String']);
      if (data.hasOwnProperty('registeredAt__between'))
        obj.registeredAtBetween = ApiClient.convertToType(data['registeredAt__between'], 'String');
      if (data.hasOwnProperty('adComputerQuery__contains'))
        obj.adComputerQueryContains = ApiClient.convertToType(data['adComputerQuery__contains'], ['String']);
      if (data.hasOwnProperty('hasLocalConfiguration'))
        obj.hasLocalConfiguration = ApiClient.convertToType(data['hasLocalConfiguration'], 'Boolean');
      if (data.hasOwnProperty('adUserQuery__contains'))
        obj.adUserQueryContains = ApiClient.convertToType(data['adUserQuery__contains'], ['String']);
      if (data.hasOwnProperty('query'))
        obj.query = ApiClient.convertToType(data['query'], 'String');
      if (data.hasOwnProperty('cloudProvider'))
        obj.cloudProvider = ApiClient.convertToType(data['cloudProvider'], ['String']);
      if (data.hasOwnProperty('cloudImage__contains'))
        obj.cloudImageContains = ApiClient.convertToType(data['cloudImage__contains'], ['String']);
      if (data.hasOwnProperty('appsVulnerabilityStatusesNin'))
        obj.appsVulnerabilityStatusesNin = ApiClient.convertToType(data['appsVulnerabilityStatusesNin'], ['String']);
      if (data.hasOwnProperty('scanStatusesNin'))
        obj.scanStatusesNin = ApiClient.convertToType(data['scanStatusesNin'], ['String']);
      if (data.hasOwnProperty('adComputerMember__contains'))
        obj.adComputerMemberContains = ApiClient.convertToType(data['adComputerMember__contains'], ['String']);
      if (data.hasOwnProperty('rangerVersions'))
        obj.rangerVersions = ApiClient.convertToType(data['rangerVersions'], ['String']);
      if (data.hasOwnProperty('machineTypes'))
        obj.machineTypes = ApiClient.convertToType(data['machineTypes'], ['String']);
      if (data.hasOwnProperty('locationIds'))
        obj.locationIds = ApiClient.convertToType(data['locationIds'], ['String']);
      if (data.hasOwnProperty('locationIdsNin'))
        obj.locationIdsNin = ApiClient.convertToType(data['locationIdsNin'], ['String']);
      if (data.hasOwnProperty('missingPermissionsNin'))
        obj.missingPermissionsNin = ApiClient.convertToType(data['missingPermissionsNin'], ['String']);
      if (data.hasOwnProperty('threatRebootRequired'))
        obj.threatRebootRequired = ApiClient.convertToType(data['threatRebootRequired'], ['Boolean']);
      if (data.hasOwnProperty('serialNumber__contains'))
        obj.serialNumberContains = ApiClient.convertToType(data['serialNumber__contains'], ['String']);
      if (data.hasOwnProperty('lastSuccessfulScanDate__between'))
        obj.lastSuccessfulScanDateBetween = ApiClient.convertToType(data['lastSuccessfulScanDate__between'], 'String');
      if (data.hasOwnProperty('lastActiveDate__between'))
        obj.lastActiveDateBetween = ApiClient.convertToType(data['lastActiveDate__between'], 'String');
      if (data.hasOwnProperty('networkQuarantineEnabled'))
        obj.networkQuarantineEnabled = ApiClient.convertToType(data['networkQuarantineEnabled'], ['Boolean']);
      if (data.hasOwnProperty('cloudTags__contains'))
        obj.cloudTagsContains = ApiClient.convertToType(data['cloudTags__contains'], ['String']);
      if (data.hasOwnProperty('encryptedApplications'))
        obj.encryptedApplications = ApiClient.convertToType(data['encryptedApplications'], 'Boolean');
      if (data.hasOwnProperty('isUninstalled'))
        obj.isUninstalled = ApiClient.convertToType(data['isUninstalled'], ['Boolean']);
      if (data.hasOwnProperty('networkInterfacePhysical__contains'))
        obj.networkInterfacePhysicalContains = ApiClient.convertToType(data['networkInterfacePhysical__contains'], ['String']);
      if (data.hasOwnProperty('operationalStates'))
        obj.operationalStates = ApiClient.convertToType(data['operationalStates'], ['String']);
      if (data.hasOwnProperty('adUserName__contains'))
        obj.adUserNameContains = ApiClient.convertToType(data['adUserName__contains'], ['String']);
      if (data.hasOwnProperty('osTypesNin'))
        obj.osTypesNin = ApiClient.convertToType(data['osTypesNin'], ['String']);
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('awsSubnetIds__contains'))
        obj.awsSubnetIdsContains = ApiClient.convertToType(data['awsSubnetIds__contains'], ['String']);
      if (data.hasOwnProperty('osVersion__contains'))
        obj.osVersionContains = ApiClient.convertToType(data['osVersion__contains'], ['String']);
      if (data.hasOwnProperty('externalIp__contains'))
        obj.externalIpContains = ApiClient.convertToType(data['externalIp__contains'], ['String']);
      if (data.hasOwnProperty('awsSecurityGroups__contains'))
        obj.awsSecurityGroupsContains = ApiClient.convertToType(data['awsSecurityGroups__contains'], ['String']);
      if (data.hasOwnProperty('k8sNodeName__contains'))
        obj.k8sNodeNameContains = ApiClient.convertToType(data['k8sNodeName__contains'], ['String']);
      if (data.hasOwnProperty('hasTags'))
        obj.hasTags = ApiClient.convertToType(data['hasTags'], 'Boolean');
      if (data.hasOwnProperty('agentNamespace__contains'))
        obj.agentNamespaceContains = ApiClient.convertToType(data['agentNamespace__contains'], ['String']);
      if (data.hasOwnProperty('networkInterfaceInet__contains'))
        obj.networkInterfaceInetContains = ApiClient.convertToType(data['networkInterfaceInet__contains'], ['String']);
      if (data.hasOwnProperty('computerName__contains'))
        obj.computerNameContains = ApiClient.convertToType(data['computerName__contains'], ['String']);
      if (data.hasOwnProperty('cloudNetwork__contains'))
        obj.cloudNetworkContains = ApiClient.convertToType(data['cloudNetwork__contains'], ['String']);
      if (data.hasOwnProperty('remoteProfilingStates'))
        obj.remoteProfilingStates = ApiClient.convertToType(data['remoteProfilingStates'], ['String']);
      if (data.hasOwnProperty('filteredGroupIds'))
        obj.filteredGroupIds = ApiClient.convertToType(data['filteredGroupIds'], ['String']);
      if (data.hasOwnProperty('agentPodName__contains'))
        obj.agentPodNameContains = ApiClient.convertToType(data['agentPodName__contains'], ['String']);
      if (data.hasOwnProperty('userActionsNeededNin'))
        obj.userActionsNeededNin = ApiClient.convertToType(data['userActionsNeededNin'], ['String']);
      if (data.hasOwnProperty('rangerStatuses'))
        obj.rangerStatuses = ApiClient.convertToType(data['rangerStatuses'], ['String']);
      if (data.hasOwnProperty('externalId__contains'))
        obj.externalIdContains = ApiClient.convertToType(data['externalId__contains'], ['String']);
      if (data.hasOwnProperty('consoleMigrationStatusesNin'))
        obj.consoleMigrationStatusesNin = ApiClient.convertToType(data['consoleMigrationStatusesNin'], ['String']);
      if (data.hasOwnProperty('cpuId__contains'))
        obj.cpuIdContains = ApiClient.convertToType(data['cpuId__contains'], ['String']);
      if (data.hasOwnProperty('coreCount__between'))
        obj.coreCountBetween = ApiClient.convertToType(data['coreCount__between'], 'String');
      if (data.hasOwnProperty('isUpToDate'))
        obj.isUpToDate = ApiClient.convertToType(data['isUpToDate'], 'Boolean');
      if (data.hasOwnProperty('rangerStatus'))
        obj.rangerStatus = ApiClient.convertToType(data['rangerStatus'], 'String');
      if (data.hasOwnProperty('totalMemory__between'))
        obj.totalMemoryBetween = ApiClient.convertToType(data['totalMemory__between'], 'String');
      if (data.hasOwnProperty('domains'))
        obj.domains = ApiClient.convertToType(data['domains'], ['String']);
      if (data.hasOwnProperty('awsRole__contains'))
        obj.awsRoleContains = ApiClient.convertToType(data['awsRole__contains'], ['String']);
      if (data.hasOwnProperty('lastLoggedInUserName__contains'))
        obj.lastLoggedInUserNameContains = ApiClient.convertToType(data['lastLoggedInUserName__contains'], ['String']);
      if (data.hasOwnProperty('cloudAccount__contains'))
        obj.cloudAccountContains = ApiClient.convertToType(data['cloudAccount__contains'], ['String']);
      if (data.hasOwnProperty('clusterName__contains'))
        obj.clusterNameContains = ApiClient.convertToType(data['clusterName__contains'], ['String']);
      if (data.hasOwnProperty('scanStatuses'))
        obj.scanStatuses = ApiClient.convertToType(data['scanStatuses'], ['String']);
      if (data.hasOwnProperty('liveUpdateId__contains'))
        obj.liveUpdateIdContains = ApiClient.convertToType(data['liveUpdateId__contains'], ['String']);
      if (data.hasOwnProperty('osTypes'))
        obj.osTypes = ApiClient.convertToType(data['osTypes'], ['String']);
      if (data.hasOwnProperty('appsVulnerabilityStatuses'))
        obj.appsVulnerabilityStatuses = ApiClient.convertToType(data['appsVulnerabilityStatuses'], ['String']);
      if (data.hasOwnProperty('remoteProfilingStatesNin'))
        obj.remoteProfilingStatesNin = ApiClient.convertToType(data['remoteProfilingStatesNin'], ['String']);
      if (data.hasOwnProperty('filteredSiteIds'))
        obj.filteredSiteIds = ApiClient.convertToType(data['filteredSiteIds'], ['String']);
      if (data.hasOwnProperty('userActionsNeeded'))
        obj.userActionsNeeded = ApiClient.convertToType(data['userActionsNeeded'], ['String']);
      if (data.hasOwnProperty('osArch'))
        obj.osArch = ApiClient.convertToType(data['osArch'], 'String');
      if (data.hasOwnProperty('adComputerName__contains'))
        obj.adComputerNameContains = ApiClient.convertToType(data['adComputerName__contains'], ['String']);
      if (data.hasOwnProperty('cloudInstanceId__contains'))
        obj.cloudInstanceIdContains = ApiClient.convertToType(data['cloudInstanceId__contains'], ['String']);
      if (data.hasOwnProperty('agentVersions'))
        obj.agentVersions = ApiClient.convertToType(data['agentVersions'], ['String']);
      if (data.hasOwnProperty('adQuery__contains'))
        obj.adQueryContains = ApiClient.convertToType(data['adQuery__contains'], ['String']);
      if (data.hasOwnProperty('locationEnabled'))
        obj.locationEnabled = ApiClient.convertToType(data['locationEnabled'], ['Boolean']);
      if (data.hasOwnProperty('cloudProviderNin'))
        obj.cloudProviderNin = ApiClient.convertToType(data['cloudProviderNin'], ['String']);
      if (data.hasOwnProperty('isPendingUninstall'))
        obj.isPendingUninstall = ApiClient.convertToType(data['isPendingUninstall'], 'Boolean');
      if (data.hasOwnProperty('k8sNodeLabels__contains'))
        obj.k8sNodeLabelsContains = ApiClient.convertToType(data['k8sNodeLabels__contains'], ['String']);
      if (data.hasOwnProperty('tagsData'))
        obj.tagsData = ApiClient.convertToType(data['tagsData'], 'String');
      if (data.hasOwnProperty('firewallEnabled'))
        obj.firewallEnabled = ApiClient.convertToType(data['firewallEnabled'], ['Boolean']);
      if (data.hasOwnProperty('domainsNin'))
        obj.domainsNin = ApiClient.convertToType(data['domainsNin'], ['String']);
      if (data.hasOwnProperty('gcpServiceAccount__contains'))
        obj.gcpServiceAccountContains = ApiClient.convertToType(data['gcpServiceAccount__contains'], ['String']);
      if (data.hasOwnProperty('cloudLocation__contains'))
        obj.cloudLocationContains = ApiClient.convertToType(data['cloudLocation__contains'], ['String']);
      if (data.hasOwnProperty('networkStatuses'))
        obj.networkStatuses = ApiClient.convertToType(data['networkStatuses'], ['String']);
      if (data.hasOwnProperty('k8sType__contains'))
        obj.k8sTypeContains = ApiClient.convertToType(data['k8sType__contains'], ['String']);
      if (data.hasOwnProperty('networkInterfaceGatewayMacAddress__contains'))
        obj.networkInterfaceGatewayMacAddressContains = ApiClient.convertToType(data['networkInterfaceGatewayMacAddress__contains'], ['String']);
      if (data.hasOwnProperty('cpuCount__between'))
        obj.cpuCountBetween = ApiClient.convertToType(data['cpuCount__between'], 'String');
      if (data.hasOwnProperty('operationalStatesNin'))
        obj.operationalStatesNin = ApiClient.convertToType(data['operationalStatesNin'], ['String']);
      if (data.hasOwnProperty('k8sVersion__contains'))
        obj.k8sVersionContains = ApiClient.convertToType(data['k8sVersion__contains'], ['String']);
      if (data.hasOwnProperty('installerTypes'))
        obj.installerTypes = ApiClient.convertToType(data['installerTypes'], ['String']);
      if (data.hasOwnProperty('adUserMember__contains'))
        obj.adUserMemberContains = ApiClient.convertToType(data['adUserMember__contains'], ['String']);
      if (data.hasOwnProperty('infected'))
        obj.infected = ApiClient.convertToType(data['infected'], 'Boolean');
      if (data.hasOwnProperty('missingPermissions'))
        obj.missingPermissions = ApiClient.convertToType(data['missingPermissions'], ['String']);
      if (data.hasOwnProperty('installerTypesNin'))
        obj.installerTypesNin = ApiClient.convertToType(data['installerTypesNin'], ['String']);
      if (data.hasOwnProperty('machineTypesNin'))
        obj.machineTypesNin = ApiClient.convertToType(data['machineTypesNin'], ['String']);
      if (data.hasOwnProperty('isDecommissioned'))
        obj.isDecommissioned = ApiClient.convertToType(data['isDecommissioned'], ['Boolean']);
      if (data.hasOwnProperty('rangerStatusesNin'))
        obj.rangerStatusesNin = ApiClient.convertToType(data['rangerStatusesNin'], ['String']);
      if (data.hasOwnProperty('cloudInstanceSize__contains'))
        obj.cloudInstanceSizeContains = ApiClient.convertToType(data['cloudInstanceSize__contains'], ['String']);
      if (data.hasOwnProperty('rangerVersionsNin'))
        obj.rangerVersionsNin = ApiClient.convertToType(data['rangerVersionsNin'], ['String']);
      if (data.hasOwnProperty('consoleMigrationStatuses'))
        obj.consoleMigrationStatuses = ApiClient.convertToType(data['consoleMigrationStatuses'], ['String']);
      if (data.hasOwnProperty('azureResourceGroup__contains'))
        obj.azureResourceGroupContains = ApiClient.convertToType(data['azureResourceGroup__contains'], ['String']);
      if (data.hasOwnProperty('uuid__contains'))
        obj.uuidContains = ApiClient.convertToType(data['uuid__contains'], ['String']);
      if (data.hasOwnProperty('networkStatusesNin'))
        obj.networkStatusesNin = ApiClient.convertToType(data['networkStatusesNin'], ['String']);
      if (data.hasOwnProperty('adQuery'))
        obj.adQuery = ApiClient.convertToType(data['adQuery'], 'String');
    }
    return obj;
  }

  /**
   * Agent versions not to include
   * @member {Array.<String>} agentVersionsNin
   */
  exports.prototype.agentVersionsNin = undefined;

  /**
   * Date range for first registration time (format: <from_timestamp>-<to_timestamp>, inclusive)
   * @member {String} registeredAtBetween
   */
  exports.prototype.registeredAtBetween = undefined;

  /**
   * Free-text filter by Active Directory computer name or its groups (supports multiple values)
   * @member {Array.<String>} adComputerQueryContains
   */
  exports.prototype.adComputerQueryContains = undefined;

  /**
   * Agent has a local configuration set
   * @member {Boolean} hasLocalConfiguration
   */
  exports.prototype.hasLocalConfiguration = undefined;

  /**
   * Free-text filter by Active Directory computer name or its groups (supports multiple values)
   * @member {Array.<String>} adUserQueryContains
   */
  exports.prototype.adUserQueryContains = undefined;

  /**
   * A free-text search term, will match applicable attributes (sub-string match). Note: Device's physical addresses will be matched if they start with the search term only (no match if they contain the term).
   * @member {String} query
   */
  exports.prototype.query = undefined;

  /**
   * Agents from which cloud provider
   * @member {Array.<String>} cloudProvider
   */
  exports.prototype.cloudProvider = undefined;

  /**
   * Free-text filter by cloud image (supports multiple values)
   * @member {Array.<String>} cloudImageContains
   */
  exports.prototype.cloudImageContains = undefined;

  /**
   * Apps vulnerability status nin
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.AppsVulnerabilityStatusesNinEnum>} appsVulnerabilityStatusesNin
   */
  exports.prototype.appsVulnerabilityStatusesNin = undefined;

  /**
   * Not included scan statuses
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.ScanStatusesNinEnum>} scanStatusesNin
   */
  exports.prototype.scanStatusesNin = undefined;

  /**
   * Free-text filter by Active Directory computer groups string (supports multiple values)
   * @member {Array.<String>} adComputerMemberContains
   */
  exports.prototype.adComputerMemberContains = undefined;

  /**
   * Ranger versions to include
   * @member {Array.<String>} rangerVersions
   */
  exports.prototype.rangerVersions = undefined;

  /**
   * Included machine types
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.MachineTypesEnum>} machineTypes
   */
  exports.prototype.machineTypes = undefined;

  /**
   * Include only Agents reporting these locations
   * @member {Array.<String>} locationIds
   */
  exports.prototype.locationIds = undefined;

  /**
   * Do not include only Agents reporting these locations
   * @member {Array.<String>} locationIdsNin
   */
  exports.prototype.locationIdsNin = undefined;

  /**
   * Excluded missing permissions
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.MissingPermissionsNinEnum>} missingPermissionsNin
   */
  exports.prototype.missingPermissionsNin = undefined;

  /**
   * Has at least one threat with at least one mitigation action pending reboot to succeed
   * @member {Array.<Boolean>} threatRebootRequired
   */
  exports.prototype.threatRebootRequired = undefined;

  /**
   * Free-text filter by Serial Number (supports multiple values)
   * @member {Array.<String>} serialNumberContains
   */
  exports.prototype.serialNumberContains = undefined;

  /**
   * Date range for last successful full disk scan(format: <from_timestamp>-<to_timestamp>, inclusive)
   * @member {String} lastSuccessfulScanDateBetween
   */
  exports.prototype.lastSuccessfulScanDateBetween = undefined;

  /**
   * Date range for last active date(format: <from_timestamp>-<to_timestamp>, inclusive)
   * @member {String} lastActiveDateBetween
   */
  exports.prototype.lastActiveDateBetween = undefined;

  /**
   * The agents supports Network Quarantine Control and its enabled for the agent's group
   * @member {Array.<Boolean>} networkQuarantineEnabled
   */
  exports.prototype.networkQuarantineEnabled = undefined;

  /**
   * Free-text filter by cloud tags (supports multiple values)
   * @member {Array.<String>} cloudTagsContains
   */
  exports.prototype.cloudTagsContains = undefined;

  /**
   * Disk encryption status
   * @member {Boolean} encryptedApplications
   */
  exports.prototype.encryptedApplications = undefined;

  /**
   * Include installed, uninstalled or both
   * @member {Array.<Boolean>} isUninstalled
   */
  exports.prototype.isUninstalled = undefined;

  /**
   * Free-text filter by MAC address (supports multiple values)
   * @member {Array.<String>} networkInterfacePhysicalContains
   */
  exports.prototype.networkInterfacePhysicalContains = undefined;

  /**
   * Agent operational state
   * @member {Array.<String>} operationalStates
   */
  exports.prototype.operationalStates = undefined;

  /**
   * Free-text filter by Active Directory username string (supports multiple values)
   * @member {Array.<String>} adUserNameContains
   */
  exports.prototype.adUserNameContains = undefined;

  /**
   * Not included OS types
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.OsTypesNinEnum>} osTypesNin
   */
  exports.prototype.osTypesNin = undefined;

  /**
   * Include only active Agents
   * @member {Boolean} isActive
   */
  exports.prototype.isActive = undefined;

  /**
   * Free-text filter by aws subnet ids (supports multiple values)
   * @member {Array.<String>} awsSubnetIdsContains
   */
  exports.prototype.awsSubnetIdsContains = undefined;

  /**
   * Free-text filter by OS full name and version (supports multiple values)
   * @member {Array.<String>} osVersionContains
   */
  exports.prototype.osVersionContains = undefined;

  /**
   * Free-text filter by visible IP (supports multiple values)
   * @member {Array.<String>} externalIpContains
   */
  exports.prototype.externalIpContains = undefined;

  /**
   * Free-text filter by aws securityGroups(supports multiple values)
   * @member {Array.<String>} awsSecurityGroupsContains
   */
  exports.prototype.awsSecurityGroupsContains = undefined;

  /**
   * Free-text filter by K8s node name (supports multiple values)
   * @member {Array.<String>} k8sNodeNameContains
   */
  exports.prototype.k8sNodeNameContains = undefined;

  /**
   * Include only Agents that have any tags assigned if True, or none if False
   * @member {Boolean} hasTags
   */
  exports.prototype.hasTags = undefined;

  /**
   * Free-text filter by agent namespace (supports multiple values)
   * @member {Array.<String>} agentNamespaceContains
   */
  exports.prototype.agentNamespaceContains = undefined;

  /**
   * Free-text filter by local IP (supports multiple values)
   * @member {Array.<String>} networkInterfaceInetContains
   */
  exports.prototype.networkInterfaceInetContains = undefined;

  /**
   * Free-text filter by computer name (supports multiple values)
   * @member {Array.<String>} computerNameContains
   */
  exports.prototype.computerNameContains = undefined;

  /**
   * Free-text filter by cloud network (supports multiple values)
   * @member {Array.<String>} cloudNetworkContains
   */
  exports.prototype.cloudNetworkContains = undefined;

  /**
   * Agent remote profiling state
   * @member {Array.<String>} remoteProfilingStates
   */
  exports.prototype.remoteProfilingStates = undefined;

  /**
   * List of Group IDs to filter by
   * @member {Array.<String>} filteredGroupIds
   */
  exports.prototype.filteredGroupIds = undefined;

  /**
   * Free-text filter by agent pod name (supports multiple values)
   * @member {Array.<String>} agentPodNameContains
   */
  exports.prototype.agentPodNameContains = undefined;

  /**
   * Excluded pending user actions
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.UserActionsNeededNinEnum>} userActionsNeededNin
   */
  exports.prototype.userActionsNeededNin = undefined;

  /**
   * Status of Ranger
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.RangerStatusesEnum>} rangerStatuses
   */
  exports.prototype.rangerStatuses = undefined;

  /**
   * Free-text filter by external ID (Customer ID)
   * @member {Array.<String>} externalIdContains
   */
  exports.prototype.externalIdContains = undefined;

  /**
   * Migration status nin
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.ConsoleMigrationStatusesNinEnum>} consoleMigrationStatusesNin
   */
  exports.prototype.consoleMigrationStatusesNin = undefined;

  /**
   * Free-text filter by CPU name (supports multiple values)
   * @member {Array.<String>} cpuIdContains
   */
  exports.prototype.cpuIdContains = undefined;

  /**
   * Possible number of CPU cores (inclusive)
   * @member {String} coreCountBetween
   */
  exports.prototype.coreCountBetween = undefined;

  /**
   * Include only Agents with updated software
   * @member {Boolean} isUpToDate
   */
  exports.prototype.isUpToDate = undefined;

  /**
   * [DEPRECATED] Use rangerStatuses.
   * @member {module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.RangerStatusEnum} rangerStatus
   */
  exports.prototype.rangerStatus = undefined;

  /**
   * Total memory range (GB, inclusive)
   * @member {String} totalMemoryBetween
   */
  exports.prototype.totalMemoryBetween = undefined;

  /**
   * Included network domains
   * @member {Array.<String>} domains
   */
  exports.prototype.domains = undefined;

  /**
   * Free-text filter by aws role(supports multiple values)
   * @member {Array.<String>} awsRoleContains
   */
  exports.prototype.awsRoleContains = undefined;

  /**
   * Free-text filter by username (supports multiple values)
   * @member {Array.<String>} lastLoggedInUserNameContains
   */
  exports.prototype.lastLoggedInUserNameContains = undefined;

  /**
   * Free-text filter by cloud account (supports multiple values)
   * @member {Array.<String>} cloudAccountContains
   */
  exports.prototype.cloudAccountContains = undefined;

  /**
   * Free-text filter by cluster name (supports multiple values)
   * @member {Array.<String>} clusterNameContains
   */
  exports.prototype.clusterNameContains = undefined;

  /**
   * Included scan statuses
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.ScanStatusesEnum>} scanStatuses
   */
  exports.prototype.scanStatuses = undefined;

  /**
   * Free-text filter by live update ID (supports multiple values)
   * @member {Array.<String>} liveUpdateIdContains
   */
  exports.prototype.liveUpdateIdContains = undefined;

  /**
   * Included OS types
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.OsTypesEnum>} osTypes
   */
  exports.prototype.osTypes = undefined;

  /**
   * Apps vulnerability status in
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.AppsVulnerabilityStatusesEnum>} appsVulnerabilityStatuses
   */
  exports.prototype.appsVulnerabilityStatuses = undefined;

  /**
   * Do not include these Agent remote profiling states
   * @member {Array.<String>} remoteProfilingStatesNin
   */
  exports.prototype.remoteProfilingStatesNin = undefined;

  /**
   * List of Site IDs to filter by
   * @member {Array.<String>} filteredSiteIds
   */
  exports.prototype.filteredSiteIds = undefined;

  /**
   * Included pending user actions
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.UserActionsNeededEnum>} userActionsNeeded
   */
  exports.prototype.userActionsNeeded = undefined;

  /**
   * OS architecture
   * @member {module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.OsArchEnum} osArch
   */
  exports.prototype.osArch = undefined;

  /**
   * Free-text filter by Active Directory computer name string (supports multiple values)
   * @member {Array.<String>} adComputerNameContains
   */
  exports.prototype.adComputerNameContains = undefined;

  /**
   * Free-text filter by cloud instance id(supports multiple values)
   * @member {Array.<String>} cloudInstanceIdContains
   */
  exports.prototype.cloudInstanceIdContains = undefined;

  /**
   * Agent versions to include
   * @member {Array.<String>} agentVersions
   */
  exports.prototype.agentVersions = undefined;

  /**
   * Free-text filter by Active Directory string (supports multiple values)
   * @member {Array.<String>} adQueryContains
   */
  exports.prototype.adQueryContains = undefined;

  /**
   * The agents supports Location Awareness and it is enabled for the agent's group
   * @member {Array.<Boolean>} locationEnabled
   */
  exports.prototype.locationEnabled = undefined;

  /**
   * Exclude Agents from these cloud provider
   * @member {Array.<String>} cloudProviderNin
   */
  exports.prototype.cloudProviderNin = undefined;

  /**
   * Include only Agents with pending uninstall requests
   * @member {Boolean} isPendingUninstall
   */
  exports.prototype.isPendingUninstall = undefined;

  /**
   * Free-text filter by K8s node labels (supports multiple values)
   * @member {Array.<String>} k8sNodeLabelsContains
   */
  exports.prototype.k8sNodeLabelsContains = undefined;

  /**
   * Filter agents by their assigned tags. Given in form of a JSON where each key represents a tag key, and each value represents a list of string values to filter by. To filter by unassigned tag values, use __nin suffix in the tag key.
   * @member {String} tagsData
   */
  exports.prototype.tagsData = undefined;

  /**
   * The agents supports Firewall Control and it is enabled for the agent's group
   * @member {Array.<Boolean>} firewallEnabled
   */
  exports.prototype.firewallEnabled = undefined;

  /**
   * Not included network domains
   * @member {Array.<String>} domainsNin
   */
  exports.prototype.domainsNin = undefined;

  /**
   * Free-text filter by gcp service account (supports multiple values)
   * @member {Array.<String>} gcpServiceAccountContains
   */
  exports.prototype.gcpServiceAccountContains = undefined;

  /**
   * Free-text filter by cloud location (supports multiple values)
   * @member {Array.<String>} cloudLocationContains
   */
  exports.prototype.cloudLocationContains = undefined;

  /**
   * Included network statuses
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.NetworkStatusesEnum>} networkStatuses
   */
  exports.prototype.networkStatuses = undefined;

  /**
   * Free-text filter by K8s type(supports multiple values)
   * @member {Array.<String>} k8sTypeContains
   */
  exports.prototype.k8sTypeContains = undefined;

  /**
   * Free-text filter by Gateway MAC address (supports multiple values)
   * @member {Array.<String>} networkInterfaceGatewayMacAddressContains
   */
  exports.prototype.networkInterfaceGatewayMacAddressContains = undefined;

  /**
   * Possible number of CPU cores (inclusive)
   * @member {String} cpuCountBetween
   */
  exports.prototype.cpuCountBetween = undefined;

  /**
   * Do not include these Agent operational states
   * @member {Array.<String>} operationalStatesNin
   */
  exports.prototype.operationalStatesNin = undefined;

  /**
   * Free-text filter by K8s version (supports multiple values)
   * @member {Array.<String>} k8sVersionContains
   */
  exports.prototype.k8sVersionContains = undefined;

  /**
   * Include only Agents installed with these package types
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.InstallerTypesEnum>} installerTypes
   */
  exports.prototype.installerTypes = undefined;

  /**
   * Free-text filter by Active Directory user groups string (supports multiple values)
   * @member {Array.<String>} adUserMemberContains
   */
  exports.prototype.adUserMemberContains = undefined;

  /**
   * Include only Agents with at least one active threat
   * @member {Boolean} infected
   */
  exports.prototype.infected = undefined;

  /**
   * Included missing permissions
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.MissingPermissionsEnum>} missingPermissions
   */
  exports.prototype.missingPermissions = undefined;

  /**
   * Exclude Agents installed with these package types
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.InstallerTypesNinEnum>} installerTypesNin
   */
  exports.prototype.installerTypesNin = undefined;

  /**
   * Not included machine types
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.MachineTypesNinEnum>} machineTypesNin
   */
  exports.prototype.machineTypesNin = undefined;

  /**
   * Include active, decommissioned or both
   * @member {Array.<Boolean>} isDecommissioned
   */
  exports.prototype.isDecommissioned = undefined;

  /**
   * Do not include these Ranger Statuses
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.RangerStatusesNinEnum>} rangerStatusesNin
   */
  exports.prototype.rangerStatusesNin = undefined;

  /**
   * Free-text filter by cloud instance size(supports multiple values)
   * @member {Array.<String>} cloudInstanceSizeContains
   */
  exports.prototype.cloudInstanceSizeContains = undefined;

  /**
   * Ranger versions not to include
   * @member {Array.<String>} rangerVersionsNin
   */
  exports.prototype.rangerVersionsNin = undefined;

  /**
   * Migration status in
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.ConsoleMigrationStatusesEnum>} consoleMigrationStatuses
   */
  exports.prototype.consoleMigrationStatuses = undefined;

  /**
   * Free-text filter by azure resource group(supports multiple values)
   * @member {Array.<String>} azureResourceGroupContains
   */
  exports.prototype.azureResourceGroupContains = undefined;

  /**
   * Free-text filter by Agent UUID (supports multiple values)
   * @member {Array.<String>} uuidContains
   */
  exports.prototype.uuidContains = undefined;

  /**
   * Included network statuses
   * @member {Array.<module:model/FiltersFiltersUpdateFilterSchemaDataFilterFields.NetworkStatusesNinEnum>} networkStatusesNin
   */
  exports.prototype.networkStatusesNin = undefined;

  /**
   * An Active Directory query string
   * @member {String} adQuery
   */
  exports.prototype.adQuery = undefined;



  /**
   * Allowed values for the <code>appsVulnerabilityStatusesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AppsVulnerabilityStatusesNinEnum = {
    /**
     * value: "patch_required"
     * @const
     */
    patchRequired: "patch_required",

    /**
     * value: "up_to_date"
     * @const
     */
    upToDate: "up_to_date",

    /**
     * value: "not_applicable"
     * @const
     */
    notApplicable: "not_applicable"
  };


  /**
   * Allowed values for the <code>scanStatusesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ScanStatusesNinEnum = {
    /**
     * value: "none"
     * @const
     */
    none: "none",

    /**
     * value: "started"
     * @const
     */
    started: "started",

    /**
     * value: "aborted"
     * @const
     */
    aborted: "aborted",

    /**
     * value: "finished"
     * @const
     */
    finished: "finished"
  };


  /**
   * Allowed values for the <code>machineTypes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MachineTypesEnum = {
    /**
     * value: "unknown"
     * @const
     */
    unknown: "unknown",

    /**
     * value: "desktop"
     * @const
     */
    desktop: "desktop",

    /**
     * value: "laptop"
     * @const
     */
    laptop: "laptop",

    /**
     * value: "server"
     * @const
     */
    server: "server",

    /**
     * value: "kubernetes node"
     * @const
     */
    kubernetesNode: "kubernetes node",

    /**
     * value: "storage"
     * @const
     */
    storage: "storage",

    /**
     * value: "kubernetes pod"
     * @const
     */
    kubernetesPod: "kubernetes pod",

    /**
     * value: "ecs task"
     * @const
     */
    ecsTask: "ecs task"
  };


  /**
   * Allowed values for the <code>missingPermissionsNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MissingPermissionsNinEnum = {
    /**
     * value: "user_action_needed_fda"
     * @const
     */
    fda: "user_action_needed_fda",

    /**
     * value: "user_action_needed_rs_fda"
     * @const
     */
    rsFda: "user_action_needed_rs_fda",

    /**
     * value: "user_action_needed_fda_helper"
     * @const
     */
    fdaHelper: "user_action_needed_fda_helper",

    /**
     * value: "user_action_needed_fda_sentineld"
     * @const
     */
    fdaSentineld: "user_action_needed_fda_sentineld",

    /**
     * value: "user_action_needed_bluetooth_per"
     * @const
     */
    bluetoothPer: "user_action_needed_bluetooth_per",

    /**
     * value: "user_action_needed_network"
     * @const
     */
    network: "user_action_needed_network",

    /**
     * value: "user_action_needed_notifications"
     * @const
     */
    notifications: "user_action_needed_notifications"
  };


  /**
   * Allowed values for the <code>osTypesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OsTypesNinEnum = {
    /**
     * value: "windows"
     * @const
     */
    windows: "windows",

    /**
     * value: "macos"
     * @const
     */
    macos: "macos",

    /**
     * value: "linux"
     * @const
     */
    linux: "linux",

    /**
     * value: "windows_legacy"
     * @const
     */
    windowsLegacy: "windows_legacy"
  };


  /**
   * Allowed values for the <code>userActionsNeededNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UserActionsNeededNinEnum = {
    /**
     * value: "none"
     * @const
     */
    none: "none",

    /**
     * value: "user_action_needed"
     * @const
     */
    userActionNeeded: "user_action_needed",

    /**
     * value: "reboot_needed"
     * @const
     */
    rebootNeeded: "reboot_needed",

    /**
     * value: "upgrade_needed"
     * @const
     */
    upgradeNeeded: "upgrade_needed",

    /**
     * value: "incompatible_os"
     * @const
     */
    incompatibleOs: "incompatible_os",

    /**
     * value: "unprotected"
     * @const
     */
    unprotected: "unprotected",

    /**
     * value: "rebootless_without_dynamic_detection"
     * @const
     */
    rebootlessWithoutDynamicDetection: "rebootless_without_dynamic_detection",

    /**
     * value: "extended_exclusions_partially_accepted"
     * @const
     */
    extendedExclusionsPartiallyAccepted: "extended_exclusions_partially_accepted",

    /**
     * value: "reboot_required"
     * @const
     */
    rebootRequired: "reboot_required",

    /**
     * value: "pending_deprecation"
     * @const
     */
    pendingDeprecation: "pending_deprecation",

    /**
     * value: "ne_not_running"
     * @const
     */
    neNotRunning: "ne_not_running",

    /**
     * value: "ne_cf_not_active"
     * @const
     */
    neCfNotActive: "ne_cf_not_active",

    /**
     * value: "reboot_category"
     * @const
     */
    rebootCategory: "reboot_category",

    /**
     * value: "missing_permissions_category"
     * @const
     */
    missingPermissionsCategory: "missing_permissions_category",

    /**
     * value: "agent_suppressed_category"
     * @const
     */
    agentSuppressedCategory: "agent_suppressed_category",

    /**
     * value: "incompatible_os_category"
     * @const
     */
    incompatibleOsCategory: "incompatible_os_category",

    /**
     * value: "unprotected_category"
     * @const
     */
    unprotectedCategory: "unprotected_category",

    /**
     * value: "partial_functionality"
     * @const
     */
    partialFunctionality: "partial_functionality"
  };


  /**
   * Allowed values for the <code>rangerStatuses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RangerStatusesEnum = {
    /**
     * value: "NotApplicable"
     * @const
     */
    notApplicable: "NotApplicable",

    /**
     * value: "Enabled"
     * @const
     */
    enabled: "Enabled",

    /**
     * value: "Disabled"
     * @const
     */
    disabled: "Disabled"
  };


  /**
   * Allowed values for the <code>consoleMigrationStatusesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ConsoleMigrationStatusesNinEnum = {
    /**
     * value: "N/A"
     * @const
     */
    NA: "N/A",

    /**
     * value: "Pending"
     * @const
     */
    pending: "Pending",

    /**
     * value: "Migrated"
     * @const
     */
    migrated: "Migrated",

    /**
     * value: "Failed"
     * @const
     */
    failed: "Failed"
  };


  /**
   * Allowed values for the <code>rangerStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RangerStatusEnum = {
    /**
     * value: "NotApplicable"
     * @const
     */
    notApplicable: "NotApplicable",

    /**
     * value: "Enabled"
     * @const
     */
    enabled: "Enabled",

    /**
     * value: "Disabled"
     * @const
     */
    disabled: "Disabled"
  };


  /**
   * Allowed values for the <code>scanStatuses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ScanStatusesEnum = {
    /**
     * value: "none"
     * @const
     */
    none: "none",

    /**
     * value: "started"
     * @const
     */
    started: "started",

    /**
     * value: "aborted"
     * @const
     */
    aborted: "aborted",

    /**
     * value: "finished"
     * @const
     */
    finished: "finished"
  };


  /**
   * Allowed values for the <code>osTypes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OsTypesEnum = {
    /**
     * value: "windows"
     * @const
     */
    windows: "windows",

    /**
     * value: "macos"
     * @const
     */
    macos: "macos",

    /**
     * value: "linux"
     * @const
     */
    linux: "linux",

    /**
     * value: "windows_legacy"
     * @const
     */
    windowsLegacy: "windows_legacy"
  };


  /**
   * Allowed values for the <code>appsVulnerabilityStatuses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AppsVulnerabilityStatusesEnum = {
    /**
     * value: "patch_required"
     * @const
     */
    patchRequired: "patch_required",

    /**
     * value: "up_to_date"
     * @const
     */
    upToDate: "up_to_date",

    /**
     * value: "not_applicable"
     * @const
     */
    notApplicable: "not_applicable"
  };


  /**
   * Allowed values for the <code>userActionsNeeded</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UserActionsNeededEnum = {
    /**
     * value: "none"
     * @const
     */
    none: "none",

    /**
     * value: "user_action_needed"
     * @const
     */
    userActionNeeded: "user_action_needed",

    /**
     * value: "reboot_needed"
     * @const
     */
    rebootNeeded: "reboot_needed",

    /**
     * value: "upgrade_needed"
     * @const
     */
    upgradeNeeded: "upgrade_needed",

    /**
     * value: "incompatible_os"
     * @const
     */
    incompatibleOs: "incompatible_os",

    /**
     * value: "unprotected"
     * @const
     */
    unprotected: "unprotected",

    /**
     * value: "rebootless_without_dynamic_detection"
     * @const
     */
    rebootlessWithoutDynamicDetection: "rebootless_without_dynamic_detection",

    /**
     * value: "extended_exclusions_partially_accepted"
     * @const
     */
    extendedExclusionsPartiallyAccepted: "extended_exclusions_partially_accepted",

    /**
     * value: "reboot_required"
     * @const
     */
    rebootRequired: "reboot_required",

    /**
     * value: "pending_deprecation"
     * @const
     */
    pendingDeprecation: "pending_deprecation",

    /**
     * value: "ne_not_running"
     * @const
     */
    neNotRunning: "ne_not_running",

    /**
     * value: "ne_cf_not_active"
     * @const
     */
    neCfNotActive: "ne_cf_not_active",

    /**
     * value: "reboot_category"
     * @const
     */
    rebootCategory: "reboot_category",

    /**
     * value: "missing_permissions_category"
     * @const
     */
    missingPermissionsCategory: "missing_permissions_category",

    /**
     * value: "agent_suppressed_category"
     * @const
     */
    agentSuppressedCategory: "agent_suppressed_category",

    /**
     * value: "incompatible_os_category"
     * @const
     */
    incompatibleOsCategory: "incompatible_os_category",

    /**
     * value: "unprotected_category"
     * @const
     */
    unprotectedCategory: "unprotected_category",

    /**
     * value: "partial_functionality"
     * @const
     */
    partialFunctionality: "partial_functionality"
  };


  /**
   * Allowed values for the <code>osArch</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OsArchEnum = {
    /**
     * value: "32 bit"
     * @const
     */
    _32Bit: "32 bit",

    /**
     * value: "64 bit"
     * @const
     */
    _64Bit: "64 bit",

    /**
     * value: "ARM64"
     * @const
     */
    aRM64: "ARM64"
  };


  /**
   * Allowed values for the <code>networkStatuses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.NetworkStatusesEnum = {
    /**
     * value: "connected"
     * @const
     */
    connected: "connected",

    /**
     * value: "disconnected"
     * @const
     */
    disconnected: "disconnected",

    /**
     * value: "connecting"
     * @const
     */
    connecting: "connecting",

    /**
     * value: "disconnecting"
     * @const
     */
    disconnecting: "disconnecting"
  };


  /**
   * Allowed values for the <code>installerTypes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InstallerTypesEnum = {
    /**
     * value: ".msi"
     * @const
     */
    msi: ".msi",

    /**
     * value: ".exe"
     * @const
     */
    exe: ".exe",

    /**
     * value: ".deb"
     * @const
     */
    deb: ".deb",

    /**
     * value: ".rpm"
     * @const
     */
    rpm: ".rpm",

    /**
     * value: ".bsx"
     * @const
     */
    bsx: ".bsx",

    /**
     * value: ".pkg"
     * @const
     */
    pkg: ".pkg",

    /**
     * value: ".img"
     * @const
     */
    img: ".img",

    /**
     * value: "unknown"
     * @const
     */
    unknown: "unknown",

    /**
     * value: ".tar"
     * @const
     */
    tar: ".tar",

    /**
     * value: ".zip"
     * @const
     */
    zip: ".zip",

    /**
     * value: ".gz"
     * @const
     */
    gz: ".gz",

    /**
     * value: ".xz"
     * @const
     */
    xz: ".xz"
  };


  /**
   * Allowed values for the <code>missingPermissions</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MissingPermissionsEnum = {
    /**
     * value: "user_action_needed_fda"
     * @const
     */
    fda: "user_action_needed_fda",

    /**
     * value: "user_action_needed_rs_fda"
     * @const
     */
    rsFda: "user_action_needed_rs_fda",

    /**
     * value: "user_action_needed_fda_helper"
     * @const
     */
    fdaHelper: "user_action_needed_fda_helper",

    /**
     * value: "user_action_needed_fda_sentineld"
     * @const
     */
    fdaSentineld: "user_action_needed_fda_sentineld",

    /**
     * value: "user_action_needed_bluetooth_per"
     * @const
     */
    bluetoothPer: "user_action_needed_bluetooth_per",

    /**
     * value: "user_action_needed_network"
     * @const
     */
    network: "user_action_needed_network",

    /**
     * value: "user_action_needed_notifications"
     * @const
     */
    notifications: "user_action_needed_notifications"
  };


  /**
   * Allowed values for the <code>installerTypesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InstallerTypesNinEnum = {
    /**
     * value: ".msi"
     * @const
     */
    msi: ".msi",

    /**
     * value: ".exe"
     * @const
     */
    exe: ".exe",

    /**
     * value: ".deb"
     * @const
     */
    deb: ".deb",

    /**
     * value: ".rpm"
     * @const
     */
    rpm: ".rpm",

    /**
     * value: ".bsx"
     * @const
     */
    bsx: ".bsx",

    /**
     * value: ".pkg"
     * @const
     */
    pkg: ".pkg",

    /**
     * value: ".img"
     * @const
     */
    img: ".img",

    /**
     * value: "unknown"
     * @const
     */
    unknown: "unknown",

    /**
     * value: ".tar"
     * @const
     */
    tar: ".tar",

    /**
     * value: ".zip"
     * @const
     */
    zip: ".zip",

    /**
     * value: ".gz"
     * @const
     */
    gz: ".gz",

    /**
     * value: ".xz"
     * @const
     */
    xz: ".xz"
  };


  /**
   * Allowed values for the <code>machineTypesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MachineTypesNinEnum = {
    /**
     * value: "unknown"
     * @const
     */
    unknown: "unknown",

    /**
     * value: "desktop"
     * @const
     */
    desktop: "desktop",

    /**
     * value: "laptop"
     * @const
     */
    laptop: "laptop",

    /**
     * value: "server"
     * @const
     */
    server: "server",

    /**
     * value: "kubernetes node"
     * @const
     */
    kubernetesNode: "kubernetes node",

    /**
     * value: "storage"
     * @const
     */
    storage: "storage",

    /**
     * value: "kubernetes pod"
     * @const
     */
    kubernetesPod: "kubernetes pod",

    /**
     * value: "ecs task"
     * @const
     */
    ecsTask: "ecs task"
  };


  /**
   * Allowed values for the <code>rangerStatusesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RangerStatusesNinEnum = {
    /**
     * value: "NotApplicable"
     * @const
     */
    notApplicable: "NotApplicable",

    /**
     * value: "Enabled"
     * @const
     */
    enabled: "Enabled",

    /**
     * value: "Disabled"
     * @const
     */
    disabled: "Disabled"
  };


  /**
   * Allowed values for the <code>consoleMigrationStatuses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ConsoleMigrationStatusesEnum = {
    /**
     * value: "N/A"
     * @const
     */
    NA: "N/A",

    /**
     * value: "Pending"
     * @const
     */
    pending: "Pending",

    /**
     * value: "Migrated"
     * @const
     */
    migrated: "Migrated",

    /**
     * value: "Failed"
     * @const
     */
    failed: "Failed"
  };


  /**
   * Allowed values for the <code>networkStatusesNin</code> property.
   * @enum {String}
   * @readonly
   */
  exports.NetworkStatusesNinEnum = {
    /**
     * value: "connected"
     * @const
     */
    connected: "connected",

    /**
     * value: "disconnected"
     * @const
     */
    disconnected: "disconnected",

    /**
     * value: "connecting"
     * @const
     */
    connecting: "connecting",

    /**
     * value: "disconnecting"
     * @const
     */
    disconnecting: "disconnecting"
  };

  return exports;

}));
