/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.LocationsSchemasNewLocationSchemaDataServerConnectivity = factory(root.S1MgmtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LocationsSchemasNewLocationSchemaDataServerConnectivity model module.
   * @module model/LocationsSchemasNewLocationSchemaDataServerConnectivity
   * @version 2.1
   */

  /**
   * Constructs a new <code>LocationsSchemasNewLocationSchemaDataServerConnectivity</code>.
   * Identify a location by connectivity to the management server
   * @alias module:model/LocationsSchemasNewLocationSchemaDataServerConnectivity
   * @class
   * @param enabled {Boolean} Use or discard this location identifier
   */
  var exports = function(enabled) {
    this.enabled = enabled;
  };

  /**
   * Constructs a <code>LocationsSchemasNewLocationSchemaDataServerConnectivity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LocationsSchemasNewLocationSchemaDataServerConnectivity} obj Optional instance to populate.
   * @return {module:model/LocationsSchemasNewLocationSchemaDataServerConnectivity} The populated <code>LocationsSchemasNewLocationSchemaDataServerConnectivity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }

  /**
   * Use or discard this location identifier
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;

  /**
   * Server connectivity status
   * @member {module:model/LocationsSchemasNewLocationSchemaDataServerConnectivity.ValueEnum} value
   */
  exports.prototype.value = undefined;



  /**
   * Allowed values for the <code>value</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ValueEnum = {
    /**
     * value: "connected"
     * @const
     */
    connected: "connected",

    /**
     * value: "disconnected"
     * @const
     */
    disconnected: "disconnected"
  };

  return exports;

}));
