/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.RbacSchemasRolePermissions200DataPermissions = factory(root.S1MgmtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RbacSchemasRolePermissions200DataPermissions model module.
   * @module model/RbacSchemasRolePermissions200DataPermissions
   * @version 2.1
   */

  /**
   * Constructs a new <code>RbacSchemasRolePermissions200DataPermissions</code>.
   * @alias module:model/RbacSchemasRolePermissions200DataPermissions
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RbacSchemasRolePermissions200DataPermissions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RbacSchemasRolePermissions200DataPermissions} obj Optional instance to populate.
   * @return {module:model/RbacSchemasRolePermissions200DataPermissions} The populated <code>RbacSchemasRolePermissions200DataPermissions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('identifier'))
        obj.identifier = ApiClient.convertToType(data['identifier'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('additionalDescription'))
        obj.additionalDescription = ApiClient.convertToType(data['additionalDescription'], 'String');
      if (data.hasOwnProperty('disabledReasonCode'))
        obj.disabledReasonCode = ApiClient.convertToType(data['disabledReasonCode'], 'String');
      if (data.hasOwnProperty('disabledReason'))
        obj.disabledReason = ApiClient.convertToType(data['disabledReason'], 'String');
      if (data.hasOwnProperty('dependsOn'))
        obj.dependsOn = ApiClient.convertToType(data['dependsOn'], ['String']);
      if (data.hasOwnProperty('groupName'))
        obj.groupName = ApiClient.convertToType(data['groupName'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Boolean');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
    }
    return obj;
  }

  /**
   * Identifier
   * @member {String} identifier
   */
  exports.prototype.identifier = undefined;

  /**
   * Description
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * Additional description
   * @member {String} additionalDescription
   */
  exports.prototype.additionalDescription = undefined;

  /**
   * Disabled reason code
   * @member {String} disabledReasonCode
   */
  exports.prototype.disabledReasonCode = undefined;

  /**
   * Disabled reason
   * @member {String} disabledReason
   */
  exports.prototype.disabledReason = undefined;

  /**
   * Depends on
   * @member {Array.<String>} dependsOn
   */
  exports.prototype.dependsOn = undefined;

  /**
   * Group name
   * @member {String} groupName
   */
  exports.prototype.groupName = undefined;

  /**
   * Type
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * Value
   * @member {Boolean} value
   */
  exports.prototype.value = undefined;

  /**
   * Title
   * @member {String} title
   */
  exports.prototype.title = undefined;


  return exports;

}));
