/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SitesSiteResponseSchema200DataLicensesBundles', 'model/SitesSiteResponseSchema200DataLicensesModules', 'model/SitesSiteResponseSchema200DataLicensesSettings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SitesSiteResponseSchema200DataLicensesBundles'), require('./SitesSiteResponseSchema200DataLicensesModules'), require('./SitesSiteResponseSchema200DataLicensesSettings'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.SitesSiteResponseSchema200DataLicenses = factory(root.S1MgmtApi.ApiClient, root.S1MgmtApi.SitesSiteResponseSchema200DataLicensesBundles, root.S1MgmtApi.SitesSiteResponseSchema200DataLicensesModules, root.S1MgmtApi.SitesSiteResponseSchema200DataLicensesSettings);
  }
}(this, function(ApiClient, SitesSiteResponseSchema200DataLicensesBundles, SitesSiteResponseSchema200DataLicensesModules, SitesSiteResponseSchema200DataLicensesSettings) {
  'use strict';

  /**
   * The SitesSiteResponseSchema200DataLicenses model module.
   * @module model/SitesSiteResponseSchema200DataLicenses
   * @version 2.1
   */

  /**
   * Constructs a new <code>SitesSiteResponseSchema200DataLicenses</code>.
   * The site licenses
   * @alias module:model/SitesSiteResponseSchema200DataLicenses
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SitesSiteResponseSchema200DataLicenses</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SitesSiteResponseSchema200DataLicenses} obj Optional instance to populate.
   * @return {module:model/SitesSiteResponseSchema200DataLicenses} The populated <code>SitesSiteResponseSchema200DataLicenses</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('modules'))
        obj.modules = ApiClient.convertToType(data['modules'], [SitesSiteResponseSchema200DataLicensesModules]);
      if (data.hasOwnProperty('settings'))
        obj.settings = ApiClient.convertToType(data['settings'], [SitesSiteResponseSchema200DataLicensesSettings]);
      if (data.hasOwnProperty('bundles'))
        obj.bundles = ApiClient.convertToType(data['bundles'], [SitesSiteResponseSchema200DataLicensesBundles]);
    }
    return obj;
  }

  /**
   * The licenses Add-ons
   * @member {Array.<module:model/SitesSiteResponseSchema200DataLicensesModules>} modules
   */
  exports.prototype.modules = undefined;

  /**
   * The licenses Settings
   * @member {Array.<module:model/SitesSiteResponseSchema200DataLicensesSettings>} settings
   */
  exports.prototype.settings = undefined;

  /**
   * The licenses Bundles
   * @member {Array.<module:model/SitesSiteResponseSchema200DataLicensesBundles>} bundles
   */
  exports.prototype.bundles = undefined;


  return exports;

}));
