/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.SitesSitePutSchemaDataPolicyAgentUi = factory(root.S1MgmtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SitesSitePutSchemaDataPolicyAgentUi model module.
   * @module model/SitesSitePutSchemaDataPolicyAgentUi
   * @version 2.1
   */

  /**
   * Constructs a new <code>SitesSitePutSchemaDataPolicyAgentUi</code>.
   * Agent ui
   * @alias module:model/SitesSitePutSchemaDataPolicyAgentUi
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SitesSitePutSchemaDataPolicyAgentUi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SitesSitePutSchemaDataPolicyAgentUi} obj Optional instance to populate.
   * @return {module:model/SitesSitePutSchemaDataPolicyAgentUi} The populated <code>SitesSitePutSchemaDataPolicyAgentUi</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('threatPopUpNotifications'))
        obj.threatPopUpNotifications = ApiClient.convertToType(data['threatPopUpNotifications'], 'Boolean');
      if (data.hasOwnProperty('contactFreeText'))
        obj.contactFreeText = ApiClient.convertToType(data['contactFreeText'], 'String');
      if (data.hasOwnProperty('contactEmail'))
        obj.contactEmail = ApiClient.convertToType(data['contactEmail'], 'String');
      if (data.hasOwnProperty('maxEventAgeDays'))
        obj.maxEventAgeDays = ApiClient.convertToType(data['maxEventAgeDays'], 'Number');
      if (data.hasOwnProperty('showAgentWarnings'))
        obj.showAgentWarnings = ApiClient.convertToType(data['showAgentWarnings'], 'Boolean');
      if (data.hasOwnProperty('contactPhoneNumber'))
        obj.contactPhoneNumber = ApiClient.convertToType(data['contactPhoneNumber'], 'String');
      if (data.hasOwnProperty('showDeviceTab'))
        obj.showDeviceTab = ApiClient.convertToType(data['showDeviceTab'], 'Boolean');
      if (data.hasOwnProperty('devicePopUpNotifications'))
        obj.devicePopUpNotifications = ApiClient.convertToType(data['devicePopUpNotifications'], 'Boolean');
      if (data.hasOwnProperty('showSupport'))
        obj.showSupport = ApiClient.convertToType(data['showSupport'], 'Boolean');
      if (data.hasOwnProperty('showQuarantineTab'))
        obj.showQuarantineTab = ApiClient.convertToType(data['showQuarantineTab'], 'Boolean');
      if (data.hasOwnProperty('contactCompany'))
        obj.contactCompany = ApiClient.convertToType(data['contactCompany'], 'String');
      if (data.hasOwnProperty('showSuspicious'))
        obj.showSuspicious = ApiClient.convertToType(data['showSuspicious'], 'Boolean');
      if (data.hasOwnProperty('contactOther'))
        obj.contactOther = ApiClient.convertToType(data['contactOther'], 'String');
      if (data.hasOwnProperty('contactDirectMessage'))
        obj.contactDirectMessage = ApiClient.convertToType(data['contactDirectMessage'], 'String');
      if (data.hasOwnProperty('contactSupportWebsite'))
        obj.contactSupportWebsite = ApiClient.convertToType(data['contactSupportWebsite'], 'String');
      if (data.hasOwnProperty('agentUiOn'))
        obj.agentUiOn = ApiClient.convertToType(data['agentUiOn'], 'Boolean');
    }
    return obj;
  }

  /**
   * Threat pop up notifications
   * @member {Boolean} threatPopUpNotifications
   */
  exports.prototype.threatPopUpNotifications = undefined;

  /**
   * Contact free text
   * @member {String} contactFreeText
   */
  exports.prototype.contactFreeText = undefined;

  /**
   * Contact email
   * @member {String} contactEmail
   */
  exports.prototype.contactEmail = undefined;

  /**
   * Max event age days
   * @member {Number} maxEventAgeDays
   */
  exports.prototype.maxEventAgeDays = undefined;

  /**
   * Show agent warnings
   * @member {Boolean} showAgentWarnings
   */
  exports.prototype.showAgentWarnings = undefined;

  /**
   * Contact phone number
   * @member {String} contactPhoneNumber
   */
  exports.prototype.contactPhoneNumber = undefined;

  /**
   * Show device tab
   * @member {Boolean} showDeviceTab
   */
  exports.prototype.showDeviceTab = undefined;

  /**
   * Device pop up notifications
   * @member {Boolean} devicePopUpNotifications
   */
  exports.prototype.devicePopUpNotifications = undefined;

  /**
   * Show support
   * @member {Boolean} showSupport
   */
  exports.prototype.showSupport = undefined;

  /**
   * Show quarantine tab
   * @member {Boolean} showQuarantineTab
   */
  exports.prototype.showQuarantineTab = undefined;

  /**
   * Contact company
   * @member {String} contactCompany
   */
  exports.prototype.contactCompany = undefined;

  /**
   * Show suspicious
   * @member {Boolean} showSuspicious
   */
  exports.prototype.showSuspicious = undefined;

  /**
   * Contact other
   * @member {String} contactOther
   */
  exports.prototype.contactOther = undefined;

  /**
   * Contact direct message
   * @member {String} contactDirectMessage
   */
  exports.prototype.contactDirectMessage = undefined;

  /**
   * Contact support website
   * @member {String} contactSupportWebsite
   */
  exports.prototype.contactSupportWebsite = undefined;

  /**
   * Agent ui on
   * @member {Boolean} agentUiOn
   */
  exports.prototype.agentUiOn = undefined;


  return exports;

}));
