/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ThreatsSchemasThreatsIncidentSchemaData', 'model/ThreatsSchemasThreatsIncidentSchemaFilter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ThreatsSchemasThreatsIncidentSchemaData'), require('./ThreatsSchemasThreatsIncidentSchemaFilter'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.ThreatsSchemasThreatsIncidentSchema = factory(root.S1MgmtApi.ApiClient, root.S1MgmtApi.ThreatsSchemasThreatsIncidentSchemaData, root.S1MgmtApi.ThreatsSchemasThreatsIncidentSchemaFilter);
  }
}(this, function(ApiClient, ThreatsSchemasThreatsIncidentSchemaData, ThreatsSchemasThreatsIncidentSchemaFilter) {
  'use strict';

  /**
   * The ThreatsSchemasThreatsIncidentSchema model module.
   * @module model/ThreatsSchemasThreatsIncidentSchema
   * @version 2.1
   */

  /**
   * Constructs a new <code>ThreatsSchemasThreatsIncidentSchema</code>.
   * @alias module:model/ThreatsSchemasThreatsIncidentSchema
   * @class
   * @param filter {module:model/ThreatsSchemasThreatsIncidentSchemaFilter} 
   * @param data {module:model/ThreatsSchemasThreatsIncidentSchemaData} 
   */
  var exports = function(filter, data) {
    this.filter = filter;
    this.data = data;
  };

  /**
   * Constructs a <code>ThreatsSchemasThreatsIncidentSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ThreatsSchemasThreatsIncidentSchema} obj Optional instance to populate.
   * @return {module:model/ThreatsSchemasThreatsIncidentSchema} The populated <code>ThreatsSchemasThreatsIncidentSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('filter'))
        obj.filter = ThreatsSchemasThreatsIncidentSchemaFilter.constructFromObject(data['filter']);
      if (data.hasOwnProperty('data'))
        obj.data = ThreatsSchemasThreatsIncidentSchemaData.constructFromObject(data['data']);
    }
    return obj;
  }

  /**
   * @member {module:model/ThreatsSchemasThreatsIncidentSchemaFilter} filter
   */
  exports.prototype.filter = undefined;

  /**
   * @member {module:model/ThreatsSchemasThreatsIncidentSchemaData} data
   */
  exports.prototype.data = undefined;


  return exports;

}));
