/*
 * S1 MGMT API
 * SentinelOne Management Console API specification.
 *
 * OpenAPI spec version: 2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.39
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S1MgmtApi) {
      root.S1MgmtApi = {};
    }
    root.S1MgmtApi.V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate = factory(root.S1MgmtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate model module.
   * @module model/V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate
   * @version 2.1
   */

  /**
   * Constructs a new <code>V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate</code>.
   * Certificate
   * @alias module:model/V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate
   * @class
   * @param certificate {String} Certificate
   * @param passphrase {String} Passphrase
   * @param apiKey {String} Apikey
   */
  var exports = function(certificate, passphrase, apiKey) {
    this.certificate = certificate;
    this.passphrase = passphrase;
    this.apiKey = apiKey;
  };

  /**
   * Constructs a <code>V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate} obj Optional instance to populate.
   * @return {module:model/V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate} The populated <code>V21ManagementSchemasTestConnectionRequestSchemaDataWorkspaceOneConnectorAuthCertificate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('certificate'))
        obj.certificate = ApiClient.convertToType(data['certificate'], 'String');
      if (data.hasOwnProperty('passphrase'))
        obj.passphrase = ApiClient.convertToType(data['passphrase'], 'String');
      if (data.hasOwnProperty('apiKey'))
        obj.apiKey = ApiClient.convertToType(data['apiKey'], 'String');
    }
    return obj;
  }

  /**
   * Certificate
   * @member {String} certificate
   */
  exports.prototype.certificate = undefined;

  /**
   * Passphrase
   * @member {String} passphrase
   */
  exports.prototype.passphrase = undefined;

  /**
   * Apikey
   * @member {String} apiKey
   */
  exports.prototype.apiKey = undefined;


  return exports;

}));
